### ISSUE TITLE
There is no such thing as 'Debian bases' which is in FAQ and linked from the first page

### ISSUE THREAD

**Issue by hedayat** [persepolisdm/persepolisdm.github.io#14]
'Debian Bases' is wrong. It should be probably replaced with 'Debian-based Distributions'. I'm not sure if anything smaller can be used, but anyway, 'Debian-base' is wrong, it is 'Debian-based'.

**Comment by Alirezaies** [comment]
@hedayat Thanks for reporting that, we will fix that :)
